### ISSUE TITLE
Don't work hot reload

### ISSUE THREAD

**Issue by AwesomeObserver** [BenjaminDobler/ngtron#7]
Don't working hot reload via `ng run project:build-electron`

Current behaviour: when you change any file and save them, app does not reload.

Node.js - latest version
Angular 8
Angular CLI - latest version

**Comment by BenjaminDobler** [comment]
Do you change files in the renderer (angular) process or main (node) process?

Have you changed the electron.ts file?
The reloading is done by the [electron-reloader](https://github.com/sindresorhus/electron-reloader) module so this line needs to be in there:
try {
  require('electron-reloader')(module);
} catch (err) {}

**Comment by AwesomeObserver** [comment]
> Do you change files in the renderer (angular) process or main (node) process?
> 
> Have you changed the electron.ts file?
> The reloading is done by the [electron-reloader](https://github.com/sindresorhus/electron-reloader) module so this line needs to be in there:
> try {
> require('electron-reloader')(module);
> } catch (err) {}

I change Angular's component file (*component.ts, and styles files).
I don't change `electron.ts` file
