### ISSUE TITLE
What's the maintenance status of the project?

### ISSUE THREAD

**Issue by mgechev** [BenjaminDobler/ngtron#9]
Hey @BenjaminDobler, again, congrats for the great job 👏🏻

I'm planning to mention ngtron during my keynote session on AngularConnect next week. I was wondering if the project is still maintained and whether you're using it for your projects?

**Comment by BenjaminDobler** [comment]
Hey Minko,
the project is still alive and used heavily inside the company i work for. 
I made quite a lot of changes internally that i now need to port back.
Your issue motivates me to do it soon!
